### ISSUE TITLE
建议列举插件命令

### ISSUE THREAD

**Issue by Rinfair-CSP-A016** [StageGuard/SuperCourseTimetableBot#29]
虽然使用了交互式方案，但是输入识别仍然较为严格（例如 导入课表 不能和 登录超级课表 一样被识别），建议在教程中列举该插件可识别的一切指令输入以便于用户快速上手。

**Comment by StageGuard** [comment]
可以举个例子吗

**Comment by Rinfair-CSP-A016** [comment]
例如第一步是录入课表，我输录入课表没反应，修改时间表没反应，输同步课程告诉我还没有登录不能同步，这个时候我才知道第一个输入是 登录超级课表。然后我要看当天的课表，我输 查看课表 没反应，输 今日课表 才有反应。有新课了，输更新课表没反应，要输 同步课程 才有反应。最好是列出来一些指令的范围，这样用户才知道该发什么。
