### ISSUE TITLE
同步了错误学年和学期的课程表

### ISSUE THREAD

**Issue by AiconMomo** [StageGuard/SuperCourseTimetableBot#30]
本学期为2022-2023学年第一学期，但是机器人获取了2021-2022学年第二学期的课程表，在删除了超级课程表客户端的2021-2022学年的数据后，机器人仍然选择获取2021-2022学年第二学期的课程表，但因为数据缺失，报错同步失败。

**Comment by StageGuard** [comment]
设定为 9 月 1 日后才为冬季学期，具体判断逻辑在 https://github.com/StageGuard/SuperCourseTimetableBot/blob/main/src/main/kotlin/me/stageguard/sctimetable/service/TimeProviderService.kt#L93

**Comment by AiconMomo** [comment]
好的，感谢作者大大
