### ISSUE TITLE
关于如何修改工作的bot的问题

### ISSUE THREAD

**Issue by knightsheep** [StageGuard/SuperCourseTimetableBot#31]
尊敬的作者你好：
我想请问一下如何修改工作的bot，我在SG.SCTimeTableBotConfig.yml文件中修改用于工作的bot之后，重新运行mirai时仍然是以前的bot，请问这种情况如何解决

**Comment by StageGuard** [comment]
要完全关闭 mirai-console 后再修改配置文件

**Comment by knightsheep** [comment]
好的 解决了
