### ISSUE TITLE
输入密码后控制台报错

### ISSUE THREAD

**Issue by R1nkwh** [StageGuard/SuperCourseTimetableBot#33]
![image](https://user-images.githubusercontent.com/111223971/206885958-9da83848-e36c-44b2-a42e-de92cabc5d2a.png)

**Comment by StageGuard** [comment]
插件在旧版mirai编译，不适用新版的 console，晚上我重新编译一下。

**Comment by R1nkwh** [comment]
麻烦佬了🥰

**Comment by StageGuard** [comment]
https://github.com/StageGuard/SuperCourseTimetableBot/releases/tag/v18
