### ISSUE TITLE
登录成功后在同步课程表信息时却显示同步失败，未登录

### ISSUE THREAD

**Issue by R1nkwh** [StageGuard/SuperCourseTimetableBot#34]
如图![IMG_20221212_030416.jpg](https://user-images.githubusercontent.com/111223971/206923586-30eff781-46d3-4675-8d9d-6e05684eb397.jpg)

**Comment by R1nkwh** [comment]
![image](https://user-images.githubusercontent.com/111223971/206952368-bb26da63-b65c-468a-a0c9-f657b5e7b9af.png)
这是控制台提示的信息

**Comment by StageGuard** [comment]
jSessionId是空的，可能是改了登录凭证返回方式

**Comment by R1nkwh** [comment]
好嘞

**Comment by StageGuard** [comment]
试一下新发版

**Comment by R1nkwh** [comment]
成功解决了✌🏻
